In [38]:
import random
from datetime import timedelta
import numpy as np
import pandas as pd
from faker import Faker
fake = Faker()
from pathlib import Path 
random.seed(42)
np.random.seed(42)
OUTPUT_DIR = Path('../Datasources')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
df = pd.read_parquet(OUTPUT_DIR/"recommendation_logs.parquet")
df[df['rating'].notna()]

,recommendation_id,user_id,content_id,recommendation_timestamp,recommendation_type,recommendation_rank,recommendation_reason,device,clicked,watch_started,watch_time_seconds,completed,rating
12,REC000000013,USR00000001,CNT0030962,2024-12-14 13:55:01.494406,Personalized,13,Based on your viewing history,Mobile,True,True,1237,True,4.0
13,REC000000014,USR00000001,CNT0038109,2024-12-14 13:55:01.494406,Personalized,14,Based on your viewing history,Web,True,True,5184,True,4.0
15,REC000000016,USR00000002,CNT0024400,2020-01-28 18:48:06.465691,Personalized,1,Based on your viewing history,Mobile,True,True,2742,True,5.0
49,REC000000050,USR00000005,CNT0035392,2021-04-09 08:24:55.717393,Personalized,4,Based on your viewing history,Mobile,True,True,6530,True,3.0
61,REC000000062,USR00000006,CNT0021186,2022-11-21 13:05:12.603557,Personalized,4,Based on your viewing history,Web,True,True,5398,True,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10000616,REC010000617,USR00999997,CNT0035887,2025-11-01 04:23:12.018020,Continue Watching,3,Continue Watching,Mobile,True,True,4652,True,4.0
10000624,REC010000625,USR00999998,CNT0037768,2019-12-05 19:59:11.668716,Personalized,5,Based on your viewing history,Mobile,True,True,3409,True,5.0
10000635,REC010000636,USR00999999,CNT0022420,2022-07-22 22:23:47.558153,Personalized,3,Based on your viewing history,Tablet,True,True,5189,True,4.0
10000642,REC010000643,USR00999999,CNT0003196,2022-07-22 22:23:47.558153,Personalized,10,Based on your viewing history,Mobile,True,True,4836,True,3.0
10000647,REC010000648,USR01000000,CNT0031939,2026-02-06 16:53:27.254386,Personalized,5,Based on your viewing history,Web,True,True,4448,True,5.0

In [51]:
from pathlib import Path
import pandas


currency_to_usd = {
    "USD": 1.00,
    "EUR": 1.17,
    "GBP": 1.35,
    "INR": 0.012,
    "JPY": 0.0068,
    "CAD": 0.73,
    "AUD": 0.66,
    "BRL": 0.18,
    "MXN": 0.053,
    "KRW": 0.00072,
    "CNY": 0.14,
    "SGD": 0.78,
    "CHF": 1.24,
    "AED": 0.27,
    "SAR": 0.27,
    "ZAR": 0.056,
    "SEK": 0.11,
    "NOK": 0.096,
    "NZD": 0.60,
    "TRY": 0.025
}
# df = pd.DataFrame({'exchange_rates': list(currency_to_usd.values()), 'currency': list(currency_to_usd.keys())})
# df.to_parquet('../Datasources/us_exchange_rates.parquet')
pd.read_parquet('../Datasources/us_exchange_rates.parquet')

    exchange_rates currency
0          1.00000      USD
1          1.17000      EUR
2          1.35000      GBP
3          0.01200      INR
4          0.00680      JPY
5          0.73000      CAD
6          0.66000      AUD
7          0.18000      BRL
8          0.05300      MXN
9          0.00072      KRW
10         0.14000      CNY
11         0.78000      SGD
12         1.24000      CHF
13         0.27000      AED
14         0.27000      SAR
15         0.05600      ZAR
16         0.11000      SEK
17         0.09600      NOK
18         0.60000      NZD
19         0.02500      TRY

In [34]:
df["start_date"] = pd.to_datetime(
    df["start_date"]
).dt.date

df["end_date"] = pd.to_datetime(
    df["end_date"]
).dt.date
df.to_parquet(OUTPUT_DIR/"recommendation_logs.parquet")

KeyError: 'start_date'

In [40]:
import pyarrow.parquet as pq
print(pq.read_schema("../Datasources/recommendation_logs.parquet"))
print(
    df["recommendation_timestamp"]
    .apply(type)
    .value_counts()
)

recommendation_id: large_string
user_id: large_string
content_id: large_string
recommendation_timestamp: timestamp[us]
recommendation_type: large_string
recommendation_rank: int64
recommendation_reason: large_string
device: large_string
clicked: bool
watch_started: bool
watch_time_seconds: int64
completed: bool
rating: double
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [], "columns": [{"name":' + 1710
recommendation_timestamp
<class 'pandas.Timestamp'>    10000657
Name: count, dtype: int64

In [ ]:
users_cols = ['user_id',
 'first_name',
 'last_name',
 'email',
 'phone_number',
 'date_of_birth',
 'gender',
 'country',
 'state',
 'city',
 'preferred_language',
 'signup_date',
 'account_status']

content_catalog_col = ['content_id',
 'title',
 'content_type',
 'genre',
 'language',
 'release_year',
 'duration_minutes',
 'maturity_rating',
 'imdb_rating',
 'country',
 'director',
 'cast',
 'date_added_to_platform',
 'is_available']

subscription_cols = ['subscription_id',
 'user_id',
 'plan_name',
 'subscription_price',
 'currency',
 'billing_cycle',
 'start_date',
 'end_date',
 'auto_renew',
 'subscription_status']

payments_cols = ['payment_id',
 'subscription_id',
 'user_id',
 'original_due_date',
 'payment_date',
 'amount',
 'currency',
 'payment_method',
 'payment_status',
 'payment_failure_reason',
 'refund_amount',
 'renewal_number']
marketing_acquisition = ['acquisition_id',
 'user_id',
 'acquisition_date',
 'acquisition_channel',
 'campaign_type',
 'campaign_cost',
 'device',
 'country']

recommendation_logs_cols = ['recommendation_id',
 'user_id',
 'content_id',
 'recommendation_timestamp',
 'recommendation_type',
 'recommendation_rank',
 'recommendation_reason',
 'device',
 'clicked',
 'watch_started',
 'watch_time_seconds',
 'completed',
 'rating']